# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190224_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchbar2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=30)),
                ('Nameofperson', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Phoneno', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('Total_Amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Searchbar1',
        ),
    ]
