# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190302_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Medicine', models.CharField(max_length=30)),
                ('Company_Name', models.CharField(max_length=30)),
                ('Number_of_Tablet', models.IntegerField()),
                ('Location', models.CharField(max_length=30)),
                ('Phoneno', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
