# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20190303_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Medicine', models.CharField(max_length=30)),
                ('Nameofperson', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=40)),
                ('Phoneno', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('Batch_No', models.CharField(max_length=30)),
                ('Total_Amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Searchbar3',
        ),
    ]
