# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20190303_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescrition', models.FileField(upload_to='books/pdfs')),
            ],
        ),
    ]
